---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-configmap
data:
  cm_name: "DLSL Computer Engineering"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-05-14 - 02:53:28 +0000
  labels:
    app.kubernetes.io/name: quarkus-tekton-kubernetes
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-tekton-kubernetes
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app.kubernetes.io/name: quarkus-tekton-kubernetes
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-05-14 - 02:53:28 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: quarkus-tekton-kubernetes
  name: quarkus-tekton-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: quarkus-tekton-kubernetes
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-05-14 - 02:53:28 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: quarkus-tekton-kubernetes
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "CM_NAME"
              valueFrom:
                configMapKeyRef:
                  key: "cm_name"
                  name: "quarkus-configmap"
          image: ronelcoe/quarkus-tekton-kubernetes:1.0
          imagePullPolicy: Always
          name: quarkus-tekton-kubernetes
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
